services:
  app:
    container-name: rest-api-app
    build:
      context: ./
    environment:
      - PORT=${PORT:-8000}
      - AUTHOR=${AUTHOR:-a.dashchinsky}
      - VERSION=${VERSION:-1.0.0}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    image: rest-api-app:latest
